name: Build and Release Resume

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up TeX Live
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: small
          run: |
            apk add make grep
            make check-deps
            make lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up TeX Live and build PDFs
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add make
            make all

      - name: List generated files
        run: |
          ls -la build/
          du -h build/*.pdf

      - name: Check file existence
        uses: andstor/file-existence-action@v3
        with:
          files: "build/resume.pdf, build/cv.pdf, build/coverletter.pdf, build/teachingstatement.pdf"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-pdfs
          path: build/*.pdf
          retention-days: 30

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-pdfs
          path: ./build

      - name: Create release package
        run: |
          cd build
          tar -czf ../lijun_zhu_resume_$(date +%Y%m%d).tar.gz *.pdf
          cd ..

      - name: Get current date as tag
        id: get_date
        run: echo "RELEASE_TAG=v$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: Release ${{ env.RELEASE_TAG }}
          body: |
            Automated release of LaTeX resume documents built from commit ${{ github.sha }}.
            
            📄 **Documents included:**
            - `resume.pdf` - One-page resume format
            - `cv.pdf` - Full academic CV format  
            - `coverletter.pdf` - Cover letter template
            - `teachingstatement.pdf` - Teaching philosophy statement
            
            🕒 **Built on:** ${{ github.event.head_commit.timestamp }}
            🌟 **Commit:** ${{ github.event.head_commit.message }}
          files: |
            build/*.pdf
            lijun_zhu_resume_*.tar.gz
          draft: false
          prerelease: false
