name: Build and Release Resume

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Texlive and build PDFs
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add make
            make release

      - name: Check file existence
        uses: thebinaryfelix/check-file-existence-action@v1
        with:
          files: "resume.pdf, cv.pdf, coverletter.pdf, teachingstatement.pdf"

      - name: Upload Artifacts
        if: steps.check_files.outputs.exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: built-pdfs
          path: |
            resume.pdf
            cv.pdf
            coverletter.pdf
            teachingstatement.pdf

      - name: Get current date as tag
        id: get_date
        run: echo "RELEASE_TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create Release
        if: steps.check_files.outputs.exists == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: Release ${{ env.RELEASE_TAG }}
          body: |
            Automated release of resume.pdf built on ${{ github.ref_name }} at ${{ github.event.head_commit.timestamp }}.

      - name: Upload Release Asset
        if: steps.check_files.outputs.exists == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: resume.pdf # Assuming you want to release resume.pdf
          asset_name: resume.pdf
          asset_content_type: application/pdf
